config/routes.rb
Rails.application.routes.draw do
  resources :items, only: [:index, :show]
  resources :categories, only: [:show]
  resources :cart_items, only: [:create]
  resources :orders, only: [:new, :create]
  resources :users, only: [:new, :create, :show, :update]
  resources :charges

  namespace :admin do
    resources :items
    resources :categories
    resources :users, only: [:show, :update]
    resources :orders, only: [:update]
  end

  root 'welcome#index'

  put '/cart_items', to: "cart_items#update"
  delete '/cart_items', to: "cart_items#destroy"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get 'auth/:provider/callback', to: 'omniauth_sessions#create'
  get '/twitterlogin' => redirect('auth/twitter'), as: :twitter_login
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password(validations: false)
  validates :username, presence: true,
                       uniqueness: true
  validates :email, presence: true,
                    uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i },
                    if: 'provider.blank?'
  validates :first_name, :last_name, presence: true, if: 'provider.blank?'
  validates :display_name, length: { in: 2..32 },
            allow_blank: true
  validates :password, presence: true, confirmation: true, if: 'provider.blank?'
  validates :password_confirmation, presence: true, if: 'provider.blank?'
  validates :phone, format: { with: /[0-9\-\+]{9,15}/, message: "Phone number invalid." },
                    allow_blank: true
  before_save :format_phone, unless: 'phone.blank?'
  enum role: %w(default admin)

  has_many :orders

  def full_name
    "#{first_name} #{last_name}"
  end

  def total_items_purchased
    orders.map(&:total_items).reduce(:+)
  end

  def format_phone
    self.phone = self.phone.gsub(/[^0-9]/, '')
  end

  def self.find_or_create_by_auth(auth_data)
    user = User.where(provider: auth_data['provider'], uid: auth_data['uid']).first_or_create
    if user.username != auth_data["info"]["nickname"]
      user.username = auth_data["info"]["nickname"]
      user.first_name = auth_data["info"]["name"]
      user.save
    end
    user
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user

  def show
    @item = Item.new
    @category = Category.new
  end

  def update
    if @user.update valid_params
      redirect_to admin_user_path(@user), notice: "Account settings updated."
    else
      redirect_to admin_user_path(@user), alert: @user.errors.full_messages.join(", ")
    end
  end

  private

  def set_user
    @user = current_user
  end

  def valid_params
    params.require(:user).permit(
      :username,
      :password,
      :password_confirmation,
      :email,
      :first_name,
      :last_name,
      :display_name,
      :phone
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:new, :create]
  skip_before_action :require_user, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new valid_params
    if @user.save
      session[:user_id] = @user.id
      NotificationMessage.new.welcome(@user.full_name, @user.phone) if @user.phone?
      redirect_to @user, notice: "Welcome to your new Bluer Bottle Coffee account."
    else
      flash.now[:errors] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
  end

  def update
    if @user.update valid_params
      redirect_to @user, notice: "Account settings updated."
    else
      flash.now[:errors] = @user.errors.full_messages.join(", ")
      render :show
    end
  end

  private

  def set_user
    @user = current_user
  end

  def valid_params
    params.require(:user).permit(
                                  :username,
                                  :password,
                                  :password_confirmation,
                                  :email,
                                  :first_name,
                                  :last_name,
                                  :display_name,
                                  :phone
    )
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="row">
    <% if @user.provider.blank? %>
      <div class="large-4 columns">
        <%= f.label :username %>
        <%= f.text_field :username %>
      </div>
      <div class="large-4 columns">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div class="large-4 columns">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="large-4 columns">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div class="large-4 columns">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div class="large-4 columns">
      <%= f.label :display_name %>
      <%= f.text_field :display_name %>
    </div>
  </div>
  <div class="row">
    <div class="large-6 columns">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="large-6 columns">
      <%= f.label :phone %>
      <%= f.text_field :phone %>
    </div>
  </div>
  <div class="row">
    <%= f.submit style: "text-transform:uppercase", class: "large button expand" %>
  </div>
<% end %>

app/views/users/new.html.erb
<% content_for :title do %>Sign Up | Bluer Bottle Coffee<% end %>
<%= render 'form' %>
<div class="row">
    <h5 class="text-center">OR</h5>
    <%= link_to "SIGNUP WITH TWITTER", twitter_login_path, class: "large button expand" %>
</div>

app/views/users/show.html.erb
<% content_for :title do %><%= current_user.first_name %> | Bluer Bottle Coffee<% end %>
<div class="large-7 columns">
  <ul class="tabs" data-tab>
    <li class="tab-title active"><a href="#order_history">Order History</a></li>
    <li class="tab-title"><a href="#edit_account">Edit Account</a></li>
  </ul>
  <div class="tabs-content">
    <div class="content active" id="order_history">
      <table id="order_table" class="display" cellspacing="0" width="100%">
        <thead>
        <tr>
          <th width="150" class="text-center">Status</th>
          <th width="150" class="text-center">Date Ordered</th>
          <th width="100" class="text-center">Total</th>
          <th width="150"></th>
        </tr>
        </thead>
        <tbody>
        <% current_user.orders.each do |order| %>
          <tr>
            <td class="text-center">
              <p style="font-size:0.9rem; margin-bottom:1px"><%= order.status.capitalize %></p>
              <% if order.ordered? %>
                <%= form_tag charges_path do %>
                  <%= hidden_field_tag :order_id, order.id %>
                  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                          data-description="Bluer Bottle Coffee Order"
                          data-amount="<%= order.total_cost * 100 %>"
                          data-email="<%= current_user.email %>">
                  </script>
                <% end %>
              <% end %>
              <p style="font-size:0.9rem; margin-top:1px"><%= time_tag order.updated_at, format: "%b %-d, %Y %-l:%M %p" if order.status_locked? %></p>
            </td>
            <td class="text-center"><%= time_tag order.created_at, format: "%b %-d, %Y %-l:%M %p" %></td>
            <td class="text-center"><%= number_to_currency order.total_cost %></td>
            <td class="text-center">
              <a href="#" data-reveal-id="order_<%= order.id %>" class="small button">DETAILS</a>
              <div id="order_<%= order.id %>" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
                <%= render partial: 'orders/show', locals: { order: order } %>
                <a class="close-reveal-modal" aria-label="Close">&#215;</a>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="content" id="edit_account">
      <%= render 'form' %>
    </div>
  </div>
</div>
<div class="large-5 columns">
  <div class="row" data-equalizer>
    <div class="small-6 columns panel" data-equalizer-watch>
      <h3><%= current_user.full_name %></h3>
      <p style="color:#01a1dd; font-size:0.9rem"><%= current_user.email %></p>
    </div>
    <div class="small-5 columns panel text-center" data-equalizer-watch>
      <h4>Display Name</h4>
      <h3 style="color:#01a1dd"><%= current_user.display_name %></h3>
    </div>
  </div>
  <div class="row" data-equalizer>
    <div class="small-6 columns panel text-center" data-equalizer-watch>
      <h5>Coffees Purchased</h5>
      <h2 style="color:#01a1dd"><%= current_user.total_items_purchased %></h2>
    </div>
    <div class="small-5 columns panel text-center" data-equalizer-watch>
      <h5>Joined</h5>
        <h4 style="color:#01a1dd"><%= time_ago_in_words(current_user.created_at) %> ago</h4>
    </div>
  </div>
</div>