config/routes.rb
Rails.application.routes.draw do
  resources :items, only: [:index, :show]
  resources :categories, only: [:show]
  resources :cart_items, only: [:create]
  resources :orders, only: [:new, :create]
  resources :users, only: [:new, :create, :show, :update]
  resources :charges

  namespace :admin do
    resources :items
    resources :categories
    resources :users, only: [:show, :update]
    resources :orders, only: [:update]
  end

  root 'welcome#index'

  put '/cart_items', to: "cart_items#update"
  delete '/cart_items', to: "cart_items#destroy"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get 'auth/:provider/callback', to: 'omniauth_sessions#create'
  get '/twitterlogin' => redirect('auth/twitter'), as: :twitter_login
end

app/models/order.rb
class Order < ActiveRecord::Base
  include AASM
  validate :at_least_one_item
  validates :user, presence: true
  validates :status, presence: true

  belongs_to :user
  has_many :order_items
  has_many :items, through: :order_items

  enum status: %w(ordered paid cancelled completed)

  aasm :column => :status, :enum => true do
    state :ordered, :initial => true
    state :paid
    state :cancelled
    state :completed

    event :pay do
      transitions from: :ordered, to: :paid
    end

    event :cancel do
      transitions from: [:ordered, :paid], to: :cancelled
    end

    event :complete do
      transitions from: :paid, to: :completed
    end
  end

  def add_order_items(cart)
    cart.contents.each do |item_id, quantity|
      order_items.new(item_id: item_id.to_i, quantity: quantity)
    end
  end

  def total_cost
    order_items.map(&:price_subtotal).reduce(:+)
  end

  def total_items
    order_items.sum(:quantity)
  end

  def update_status(params)
    case params[:status]
      when 'pay'
        self.pay!
      when 'cancel'
        self.cancel!
      when 'complete'
        self.complete!
    end
  end

  def status_locked?
    completed? || cancelled?
  end

  private

  def at_least_one_item
    errors.add(:base, 'Your cart is empty') if order_items.empty?
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController

  def update
    @order = Order.find(params[:id])
    if @order.update_status valid_params
      NotificationMessage.new.order_status_update(@order.user.full_name, @order.user.phone, @order.status) if @order.user.phone?
      redirect_to admin_user_path(current_user), notice: "Order number #{@order.id} status updated."
    else
      redirect_to admin_user_path(current_user), alert: "Order status update failed."
    end
  end

  private

  def valid_params
    params.require(:order).permit(:status)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :require_user, only: [:new]

  def new
    @order = Order.new
    @order.add_order_items(@cart)
  end

  def create
    @order = Order.new
    @order.add_order_items(@cart)
    @order.user_id = session[:user_id]

    if @order.save
      NotificationMessage.new.order(current_user.full_name, current_user.phone, @order.total_cost) if current_user.phone?
      @cart.remove_all
      current_admin? ? redirect_to(admin_user_path(@order.user, notice: "Order Completed!")) : redirect_to(@order.user, notice: "Order Completed!")
    else
      flash.now[:errors] = @order.errors.full_messages.join(", ")
      render :new
    end
  end
end

app/views/orders/_show.html.erb
<h2 style="text-align:center">Order Details</h2>
<table class="order_table">
  <thead>
  <tr>
    <th class="text-center" width="200">Item</th>
    <th class="text-center">Description</th>
    <th class="text-center">Date</th>
    <th class="text-center">Quantity</th>
    <th class="text-center">Price</th>
    <th class="text-center">Subtotal</th>
  </tr>
  </thead>
  <tbody>
  <% order.order_items.each do |order_item| %>
    <tr>
      <td class="text-center"><%=link_to order_item.item.name, item_path(order_item.item.id) %></td>
      <td class="text-center"><%= order_item.item.description %></td>
      <td class="text-center"><%= time_tag order_item.created_at, format: "%b %-d, %Y %-l:%M %p"   %></td>
      <td class="text-center"><%= order_item.quantity %></td>
      <td class="text-center" style="text-align:left"><%= number_to_currency order_item.item.price %></td>
      <td class="text-center"><%= number_to_currency order_item.price_subtotal %></td>
    </tr>
  <% end %>
  </tbody>
  <tfoot>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td class="text-center">Total</td>
  <td class="text-center"><%= number_to_currency order.total_cost %></td>
  <h4 style="text-align:center">Status: <%= order.status.capitalize %></h4>
  </tfoot>
</table>

app/views/orders/new.html.erb
<% content_for :title do %>Cart | Bluer Bottle Coffee<% end %>
<table id="cart_table">
  <thead>
  <tr>
    <th width="150" class="text-center">Item</th>
    <th class="text-center">Description</th>
    <th class="text-center" width="150">Quantity</th>
    <th class="text-center" width="150">Price</th>
    <th class="text-center" width="150">Item Subtotal</th>
    <th class="text-center" width="50"></th>
  </tr>
  </thead>
  <tbody>
  <% @order.order_items.each do |order_item| %>
    <tr>
      <td class="text-center"><%= order_item.item.name %></td>
      <td class="text-center"><%= order_item.item.description %></td>
      <td class="text-center" id="update_quantity">
        <%= form_tag cart_items_path, method: :put do %>
          <%= select_tag :quantity, options_for_select(quantity_range(order_item), order_item.quantity), class: 'select_tag' %>
          <%= hidden_field_tag :item_id, order_item.item.id %>
          <%= submit_tag "UPDATE", class: "tiny button" %>
        <% end %>
      </td>
      <td class="text-center"><%= number_to_currency order_item.item.price %></td>
      <td class="text-center"><%= number_to_currency order_item.price_subtotal %></td>
      <td class="text-center" id="remove_items"><%= link_to "X", cart_items_path(item_id: order_item.item.id), method: :delete, style: "font-weight:900" %></td>
    </tr>
  <% end %>
  <tfoot>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td class="text-center">Order Total</td>
    <td class="text-center"><%= number_to_currency @order.total_cost %></td>
  </tfoot>
  </table>
<ul class="inline-list">
  <li><%= link_to "Continue Shopping", items_path %></li>
  <li><%= button_to "CHECKOUT", orders_path, class: "small button" %></li>
</ul>

app/views/orders/show.html.erb
<% content_for :title do %>Order Details<% end %>
<h1 style="text-align:center">Order Details</h1>
<table id="order_show">
  <thead>
  <tr>
    <th width="150">Item</th>
    <th>Description</th>
    <th width="150">Quantity</th>
    <th width="150">Price</th>
    <th>Date</th>
    <th>Status</th>
  </tr>
  </thead>
  <tbody>
  <% @order.order_items.each do |order_item| %>
    <tr>
      <td><%= order_item.item.name %></td>
      <td><%= order_item.item.description %></td>
      <td><%= order_item.quantity %></td>
      <td style="text-align:left"><%= number_to_currency order_item.item.price %></td>
      <td><%= order_item.created_at %></td>
      <td><%= @order.status %></td>
    </tr>
  <% end %>
  </table>