config/routes.rb
Rails.application.routes.draw do
  resources :items, only: [:index, :show]
  resources :categories, only: [:show]
  resources :cart_items, only: [:create]
  resources :orders, only: [:new, :create]
  resources :users, only: [:new, :create, :show, :update]
  resources :charges

  namespace :admin do
    resources :items
    resources :categories
    resources :users, only: [:show, :update]
    resources :orders, only: [:update]
  end

  root 'welcome#index'

  put '/cart_items', to: "cart_items#update"
  delete '/cart_items', to: "cart_items#destroy"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get 'auth/:provider/callback', to: 'omniauth_sessions#create'
  get '/twitterlogin' => redirect('auth/twitter'), as: :twitter_login
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  has_many :item_categories, dependent: :destroy
  has_many :items, through: :item_categories
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  skip_before_action :require_user, only: [:show]

  def create
    @category = Category.new(valid_params)

    if @category.save
      redirect_to admin_user_path(current_user), notice: "Category Created"
    else
      flash.now[:errors] = @category.errors.full_messages.join(", ")
      render 'admin/users/show'
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def valid_params
    params.require(:category).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :require_user, only: [:show]

  def show
    @category = Category.find(params[:id])
  end
end

app/views/admin/categories/_category.html.erb
<li>
  <%= link_to category.name, admin_category_path(category), class: "small button" %>
</li>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <div class="row">
    <div class="large-4 columns">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="row">
    <%= f.submit style: "text-transform:uppercase", class: "large button expand" %>
  </div>
<% end %>

app/views/admin/categories/show.html.erb
<% content_for :title do %><%= @category.name %> | Bluer Bottle Coffee<% end %>
<div>
  <ul class="button-group even-12">
    <li><%= link_to "ALL", items_path, class: "small button" %></li>
    <%= render partial: "category", collection: categories %>
  </ul>
  <ul class="small-block-grid-2 large-block-grid-4">
    <%= render partial: @category.items.active %>
  </ul>
</div>