config/routes.rb
Rails.application.routes.draw do
  resources :items, only: [:index, :show]
  resources :categories, only: [:show]
  resources :cart_items, only: [:create]
  resources :orders, only: [:new, :create]
  resources :users, only: [:new, :create, :show, :update]
  resources :charges

  namespace :admin do
    resources :items
    resources :categories
    resources :users, only: [:show, :update]
    resources :orders, only: [:update]
  end

  root 'welcome#index'

  put '/cart_items', to: "cart_items#update"
  delete '/cart_items', to: "cart_items#destroy"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get 'auth/:provider/callback', to: 'omniauth_sessions#create'
  get '/twitterlogin' => redirect('auth/twitter'), as: :twitter_login
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="contain-to-grid sticky" xmlns="http://www.w3.org/1999/html">
  <nav class="top-bar" data-topbar role="navigation" data-options="sticky_on: [medium, large]">
    <ul class="title-area">
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
    </ul>
    <div class="logo">
      <%= link_to image_tag("PBB_WhiteText_400x75.png"), root_path %>
    </div>
    <section class="top-bar-section">
      <%= render 'layouts/navigation_links' %>
    </section>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<!-- Right Nav Section -->
<ul class="center-buttons">
  <li class="divider"></li>
  <li><%= current_admin? ? link_to("SHOP", admin_items_path) : link_to("SHOP", items_path)%></li>
  <li class="divider"></li>
  <% if logged_in? %>
    <li><%= current_admin? ? link_to("#{current_user.first_name.upcase}", admin_user_path(current_user)) : link_to("#{current_user.first_name.upcase}", current_user) %></li>
    <li class="divider"></li>
    <li><%= link_to "LOGOUT", logout_path, method: :delete %></li>
    <li class="divider"></li>
  <% else %>
    <li><%= link_to "LOGIN", login_path %></li>
    <li class="divider"></li>
    <li><%= link_to "SIGNUP", new_user_path %></li>
    <li class="divider"></li>
  <% end %>
  <li><%= link_to new_order_path, :id => "cart_link"  do %>
      <%= image_tag("fi-shopping-cart.png", width: '20') %>
      <%= "(#{@cart.total_item_count})" unless @cart.contents.empty? %>
    <% end %></li>
  <li class="divider"></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "Bluer Bottle Coffee" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %>_<%= action_name %>">
<header>
  <%= render 'layouts/navigation' %>
</header>
<main role="main" style="margin-top:0.5rem; margin-left:0.5rem; margin-right:0.5rem">
  <%= render 'layouts/messages' %>

  <%= yield %>
</main>
</body>
</html>